const images = {
  logo: require('./images/logo.png'),
  google: require('./images/google.png'),
  x: require('./images/x.png'),
  eye: require('./images/eye.png'),
  eyeOff: require('./images/eye-off.png'),
  mail: require('./images/mail.png'),
  home: require('./images/home.png'),
  account: require('./images/account.png'),
  facebook: require('./images/facebook.png'),
  edit: require('./images/edit.png'),
  arrowLeft: require('./images/arrow-left.png'),
  next: require('./images/next.png'),
  walletBackground: require('./images/wallet-bg.png'),
  exchange: require('./images/exchange.png'),
  p2p: require('./images/couple.png'),
  ads: require('./images/megaphone.png'),
  plus: require('./images/plus.png'),
  like: require('./images/like.png'),
  stopwatch: require('./images/stopwatch.png'),
  gPay: require('./payment-methods/gpay.png'),
  phonepe: require('./payment-methods/phonepe.png'),
  upi: require('./payment-methods/upi.png'),
  paytm: require('./payment-methods/paytm.png'),
  imps: require('./payment-methods/imps.png'),
  receipt: require('./images/receipt.png'),
  tickSquare: require('./images/tick-square.png'),
  rating: require('./images/star.png'),
};

export { images };
