const ads: Ad[] = [
  {
    id: 'ad-1',
    user: {
      name: 'CryptoKing21',
      verified: true,
      badge: 'gold',
      trades: 1200,
      successRate: 99.2,
      rating: 98.5,
    },
    pricePerUnit: 3100000,
    cryptoId: 'btc',
    currency: 'INR',
    minLimit: 500,
    maxLimit: 200000,
    available: 0.75,
    paymentMethods: ['UPI', 'IMPS'],
    releaseTime: '15 min',
    type: 'buy',
  },
  {
    id: 'ad-2',
    user: {
      name: 'StableBro',
      verified: true,
      badge: 'purple',
      trades: 320,
      successRate: 96.4,
      rating: 91,
    },
    pricePerUnit: 91.8,
    cryptoId: 'usdt-eth',
    currency: 'INR',
    minLimit: 1000,
    maxLimit: 150000,
    available: 4300,
    paymentMethods: ['PhonePe', 'Paytm', 'UPI'],
    releaseTime: '30 min',
    type: 'sell',
  },
  {
    id: 'ad-3',
    user: {
      name: 'ShibaQueen',
      verified: false,
      badge: 'none',
      trades: 70,
      successRate: 82.5,
      rating: 74,
    },
    pricePerUnit: 0.0013,
    cryptoId: 'shib-eth',
    currency: 'INR',
    minLimit: 100,
    maxLimit: 20000,
    available: 9900000,
    paymentMethods: ['IMPS'],
    releaseTime: '10 min',
    type: 'sell',
  },
  {
    id: 'ad-4',
    user: {
      name: 'Dogelord9000',
      verified: true,
      badge: 'purple',
      trades: 880,
      successRate: 89.9,
      rating: 90.2,
    },
    pricePerUnit: 12.34,
    cryptoId: 'doge',
    currency: 'INR',
    minLimit: 250,
    maxLimit: 40000,
    available: 8000,
    paymentMethods: ['Paytm', 'Bank Transfer'],
    releaseTime: '45 min',
    type: 'buy',
  },
  {
    id: 'ad-5',
    user: {
      name: 'WrappedWizard',
      verified: false,
      badge: 'none',
      trades: 50,
      successRate: 60,
      rating: 50,
    },
    pricePerUnit: 2999990,
    cryptoId: 'wbtc',
    currency: 'INR',
    minLimit: 10000,
    maxLimit: 100000,
    available: 1.25,
    paymentMethods: ['GPay'],
    releaseTime: '60 min',
    type: 'sell',
  },
  {
    id: 'ad-6',
    user: {
      name: 'InactiveInvestor',
      verified: false,
      badge: 'none',
      trades: 0,
      successRate: 0,
      rating: 0,
    },
    pricePerUnit: 90,
    cryptoId: 'test-usdc',
    currency: 'INR',
    minLimit: 500,
    maxLimit: 1000,
    available: 10000,
    paymentMethods: ['IMPS'],
    releaseTime: '1 min',
    type: 'buy',
  },
  {
    id: 'ad-7',
    user: {
      name: 'SolMate',
      verified: true,
      badge: 'gold',
      trades: 540,
      successRate: 92,
      rating: 89.2,
    },
    pricePerUnit: 2700,
    cryptoId: 'sol',
    currency: 'INR',
    minLimit: 500,
    maxLimit: 50000,
    available: 230,
    paymentMethods: ['Bank Transfer', 'PhonePe'],
    releaseTime: '20 min',
    type: 'sell',
  },
  {
    id: 'ad-8',
    user: {
      name: 'ZeroLiquidity',
      verified: true,
      badge: 'none',
      trades: 130,
      successRate: 91,
      rating: 80,
    },
    pricePerUnit: 1,
    cryptoId: 'xyz',
    currency: 'INR',
    minLimit: 100,
    maxLimit: 500,
    available: 0,
    paymentMethods: ['UPI'],
    releaseTime: 'N/A',
    type: 'buy',
  },
  {
    id: 'ad-9',
    user: {
      name: 'ETHGiant',
      verified: true,
      badge: 'gold',
      trades: 2000,
      successRate: 99.9,
      rating: 100,
    },
    pricePerUnit: 188000,
    cryptoId: 'eth',
    currency: 'INR',
    minLimit: 5000,
    maxLimit: 250000,
    available: 3.2,
    paymentMethods: ['GPay', 'IMPS'],
    releaseTime: '5 min',
    type: 'sell',
  },
  {
    id: 'ad-10',
    user: {
      name: 'DustSeller',
      verified: false,
      badge: 'none',
      trades: 3,
      successRate: 33.3,
      rating: 20,
    },
    pricePerUnit: 89.5,
    cryptoId: 'usdt-eth',
    currency: 'INR',
    minLimit: 100,
    maxLimit: 200,
    available: 50,
    paymentMethods: ['UPI'],
    releaseTime: '30 min',
    type: 'sell',
  },
  {
    id: 'ad-11',
    user: {
      name: 'BigETHBuyer',
      verified: true,
      badge: 'gold',
      trades: 1400,
      successRate: 98.7,
      rating: 97,
    },
    pricePerUnit: 187500,
    cryptoId: 'eth',
    currency: 'INR',
    minLimit: 10000,
    maxLimit: 500000,
    available: 5,
    paymentMethods: ['UPI', 'Bank Transfer'],
    releaseTime: '10 min',
    type: 'buy',
  },
  {
    id: 'ad-12',
    user: {
      name: 'TetherGuy',
      verified: false,
      badge: 'purple',
      trades: 210,
      successRate: 94.5,
      rating: 88.4,
    },
    pricePerUnit: 92.0,
    cryptoId: 'usdt-eth',
    currency: 'INR',
    minLimit: 500,
    maxLimit: 25000,
    available: 7800,
    paymentMethods: ['GPay', 'Paytm'],
    releaseTime: '15 min',
    type: 'buy',
  },
  {
    id: 'ad-13',
    user: {
      name: 'SolScanner',
      verified: true,
      badge: 'gold',
      trades: 390,
      successRate: 95,
      rating: 91,
    },
    pricePerUnit: 2725,
    cryptoId: 'sol',
    currency: 'INR',
    minLimit: 1000,
    maxLimit: 60000,
    available: 100,
    paymentMethods: ['IMPS', 'PhonePe'],
    releaseTime: '8 min',
    type: 'buy',
  },
  {
    id: 'ad-14',
    user: {
      name: 'MemecoinBuyer',
      verified: false,
      badge: 'none',
      trades: 60,
      successRate: 80,
      rating: 70,
    },
    pricePerUnit: 0.0014,
    cryptoId: 'shib-eth',
    currency: 'INR',
    minLimit: 200,
    maxLimit: 25000,
    available: 5000000,
    paymentMethods: ['UPI'],
    releaseTime: '35 min',
    type: 'buy',
  },
  {
    id: 'ad-15',
    user: {
      name: 'WrappedFan',
      verified: true,
      badge: 'purple',
      trades: 800,
      successRate: 99,
      rating: 96,
    },
    pricePerUnit: 3020000,
    cryptoId: 'wbtc',
    currency: 'INR',
    minLimit: 5000,
    maxLimit: 75000,
    available: 0.95,
    paymentMethods: ['PhonePe', 'IMPS'],
    releaseTime: '20 min',
    type: 'buy',
  },
];

export { ads };
