import { CryptoOption } from '@/hooks/appData/useCrypto';

const ads: Ad[] = [
  {
    id: '1',
    user: {
      id: 'u1',
      name: 'SatoshiFan',
      verified: true,
      badge: 'gold',
      trades: 1240,
      successRate: 98,
      rating: 4.9,
    },
    price: 45200,
    cryptoId: 'btc',
    currency: 'INR',
    minLimit: 500,
    maxLimit: 5000,
    available: 0.75,
    payMethods: ['upi', 'imps'],
    releaseTime: '15 min',
    type: 'buy',
  },
  {
    id: '2',
    user: {
      id: 'u2',
      name: 'CryptoQueen',
      verified: true,
      badge: 'purple',
      trades: 980,
      successRate: 95,
      rating: 4.8,
    },
    price: 1.01,
    cryptoId: 'usdt',
    currency: 'INR',
    minLimit: 100,
    maxLimit: 3000,
    available: 1200,
    payMethods: ['imps'],
    releaseTime: '5 min',
    type: 'sell',
  },
  {
    id: '3',
    user: {
      id: 'u3',
      name: 'HODLMaster',
      verified: false,
      badge: 'none',
      trades: 340,
      successRate: 88,
      rating: 4.3,
    },
    price: 45350,
    cryptoId: 'btc',
    currency: 'INR',
    minLimit: 1000,
    maxLimit: 10000,
    available: 1.2,
    payMethods: ['phonepe', 'gpay'],
    releaseTime: '10 min',
    type: 'sell',
  },
  {
    id: '4',
    user: {
      id: 'u4',
      name: 'BlockTrader',
      verified: true,
      badge: 'none',
      trades: 670,
      successRate: 91,
      rating: 4.6,
    },
    price: 1.0,
    cryptoId: 'usdt',
    currency: 'INR',
    minLimit: 200,
    maxLimit: 2500,
    available: 800,
    payMethods: ['paytm', 'upi'],
    releaseTime: '20 min',
    type: 'buy',
  },
  {
    id: '5',
    user: {
      id: 'u5',
      name: 'AltcoinBoss',
      verified: false,
      badge: 'none',
      trades: 150,
      successRate: 80,
      rating: 4.0,
    },
    price: 1200,
    cryptoId: 'eth',
    currency: 'INR',
    minLimit: 300,
    maxLimit: 6000,
    available: 3.5,
    payMethods: ['imps'],
    releaseTime: '25 min',
    type: 'sell',
  },
  {
    id: '6',
    user: {
      id: 'u6',
      name: 'INRWhale',
      verified: true,
      badge: 'gold',
      trades: 2100,
      successRate: 99,
      rating: 5.0,
    },
    price: 44800,
    cryptoId: 'btc',
    currency: 'INR',
    minLimit: 100,
    maxLimit: 8000,
    available: 0.95,
    payMethods: ['imps', 'upi'],
    releaseTime: '3 min',
    type: 'buy',
  },
  {
    id: '7',
    user: {
      id: 'u7',
      name: 'FastPayer',
      verified: true,
      badge: 'purple',
      trades: 890,
      successRate: 94,
      rating: 4.7,
    },
    price: 1.02,
    cryptoId: 'usdt',
    currency: 'INR',
    minLimit: 500,
    maxLimit: 10000,
    available: 2000,
    payMethods: ['phonepe', 'gpay', 'paytm'],
    releaseTime: '8 min',
    type: 'sell',
  },
  {
    id: '8',
    user: {
      id: 'u8',
      name: 'GigaChad',
      verified: false,
      badge: 'none',
      trades: 70,
      successRate: 72,
      rating: 3.9,
    },
    price: 44500,
    cryptoId: 'btc',
    currency: 'INR',
    minLimit: 1000,
    maxLimit: 7000,
    available: 0.4,
    payMethods: ['upi'],
    releaseTime: '30 min',
    type: 'sell',
  },
  {
    id: '9',
    user: {
      id: 'u9',
      name: 'EthGuy',
      verified: true,
      badge: 'none',
      trades: 500,
      successRate: 89,
      rating: 4.5,
    },
    price: 1180,
    cryptoId: 'eth',
    currency: 'INR',
    minLimit: 200,
    maxLimit: 3000,
    available: 2.2,
    payMethods: ['upi', 'phonepe'],
    releaseTime: '12 min',
    type: 'buy',
  },
  {
    id: '10',
    user: {
      id: 'u10',
      name: 'LegendTrader',
      verified: true,
      badge: 'gold',
      trades: 3500,
      successRate: 97,
      rating: 4.95,
    },
    price: 45300,
    cryptoId: 'btc',
    currency: 'INR',
    minLimit: 1000,
    maxLimit: 15000,
    available: 2.8,
    payMethods: ['imps', 'upi'],
    releaseTime: '7 min',
    type: 'sell',
  },
  {
    id: '11',
    user: {
      id: 'u11',
      name: 'SolSniper',
      verified: false,
      badge: 'none',
      trades: 90,
      successRate: 75,
      rating: 3.8,
    },
    price: 95,
    cryptoId: 'usdt',
    currency: 'INR',
    minLimit: 100,
    maxLimit: 2000,
    available: 500,
    payMethods: ['gpay'],
    releaseTime: '18 min',
    type: 'buy',
  },
  {
    id: '12',
    user: {
      id: 'u12',
      name: 'BudgetBuyer',
      verified: true,
      badge: 'purple',
      trades: 620,
      successRate: 92,
      rating: 4.4,
    },
    price: 1.0,
    cryptoId: 'usdt',
    currency: 'INR',
    minLimit: 50,
    maxLimit: 500,
    available: 300,
    payMethods: ['gpay', 'phonepe'],
    releaseTime: '9 min',
    type: 'buy',
  },
  {
    id: '13',
    user: {
      id: 'u13',
      name: 'SteadySeller',
      verified: true,
      badge: 'none',
      trades: 430,
      successRate: 85,
      rating: 4.1,
    },
    price: 45000,
    cryptoId: 'btc',
    currency: 'INR',
    minLimit: 500,
    maxLimit: 2500,
    available: 0.6,
    payMethods: ['upi'],
    releaseTime: '22 min',
    type: 'sell',
  },
  {
    id: '14',
    user: {
      id: 'u14',
      name: 'QuickPay',
      verified: true,
      badge: 'purple',
      trades: 780,
      successRate: 96,
      rating: 4.85,
    },
    price: 1.03,
    cryptoId: 'usdt',
    currency: 'INR',
    minLimit: 150,
    maxLimit: 4000,
    available: 700,
    payMethods: ['paytm', 'phonepe'],
    releaseTime: '6 min',
    type: 'sell',
  },
  {
    id: '15',
    user: {
      id: 'u15',
      name: 'BigFish',
      verified: true,
      badge: 'gold',
      trades: 5000,
      successRate: 99,
      rating: 5.0,
    },
    price: 44950,
    cryptoId: 'btc',
    currency: 'INR',
    minLimit: 5000,
    maxLimit: 20000,
    available: 3.5,
    payMethods: ['upi'],
    releaseTime: '2 min',
    type: 'buy',
  },
];

const getFilteredAds = (adType: AdType, crypto: CryptoOption) => {
  return ads.filter((item) => {
    if (item.type !== adType) return false;

    if (crypto === 'all') return true;

    return item.cryptoId === crypto;
  });
};

const getAdById = (id: string, adType: AdType, crypto: CryptoOption) => {
  return ads.filter((item) => {
    if (item.user.id !== id) return false;

    if (item.type !== adType) return false;

    if (crypto === 'all') return true;

    return item.cryptoId === crypto;
  });
};

export { ads, getAdById, getFilteredAds };
