import SupabaseConfig from './supabase';
import { EMAIL_REGEX, NAME_REGEX, PASSWORD_REGEX, PHONE_REGEX } from './validations';

export const P2P_LISTINGS = [
  {
    id: '1',
    user: {
      name: 'BabaBitcoin',
      // avatar: require('@/assets/avatars/baba.png'),
      verified: true,
      badge: 'purple',
      trades: 562,
      successRate: 98.5,
      rating: 100.0,
    },
    pricePerUnit: 92.0,
    asset: 'USDT',
    currency: 'INR',
    minLimit: 30000,
    maxLimit: 280229,
    available: 3045.97,
    paymentMethods: ['IMPS', 'GPay', 'PhonePe', 'UPI', 'Paytm'],
    releaseTime: '45 min',
    type: 'sell',
  },
  {
    id: '2',
    user: {
      name: 'SmallShark',
      // avatar: require('@/assets/avatars/shark.png'),
      verified: true,
      badge: 'purple',
      trades: 396,
      successRate: 99.8,
      rating: 99.69,
    },
    pricePerUnit: 92.1,
    asset: 'USDT',
    currency: 'INR',
    minLimit: 200000,
    maxLimit: 1800900,
    available: 21900,
    paymentMethods: ['IMPS', 'GPay', 'PhonePe', 'Paytm'],
    releaseTime: '30 min',
    type: 'sell',
  },
  {
    id: '3',
    user: {
      name: 'CHOUDHARY-',
      // avatar: require('@/assets/avatars/choudhary.png'),
      verified: true,
      badge: 'purple',
      trades: 453,
      successRate: 100.0,
      rating: 100.0,
    },
    pricePerUnit: 92.14,
    asset: 'USDT',
    currency: 'INR',
    minLimit: 200000,
    maxLimit: 200000,
    available: 2170.61,
    paymentMethods: ['GPay', 'PhonePe'],
    releaseTime: '30 min',
    type: 'sell',
  },
  {
    id: '4',
    user: {
      name: 'CryptoKing',
      // avatar: require('@/assets/avatars/king.png'),
      verified: false,
      badge: 'none',
      trades: 189,
      successRate: 97.2,
      rating: 98.7,
    },
    pricePerUnit: 91.85,
    asset: 'USDT',
    currency: 'INR',
    minLimit: 15000,
    maxLimit: 100000,
    available: 784.2,
    paymentMethods: ['UPI', 'Paytm'],
    releaseTime: '60 min',
    type: 'buy',
  },
  {
    id: '5',
    user: {
      name: 'QuickTrades',
      // avatar: require('@/assets/avatars/quicktrades.png'),
      verified: true,
      badge: 'purple',
      trades: 1023,
      successRate: 95.4,
      rating: 97.5,
    },
    pricePerUnit: 92.5,
    asset: 'USDT',
    currency: 'INR',
    minLimit: 50000,
    maxLimit: 250000,
    available: 5000,
    paymentMethods: ['IMPS', 'PhonePe', 'GPay'],
    releaseTime: '20 min',
    type: 'buy',
  },
  {
    id: '6',
    user: {
      name: 'MoonPay',
      // avatar: require('@/assets/avatars/moonpay.png'),
      verified: false,
      badge: 'none',
      trades: 87,
      successRate: 88.0,
      rating: 90.0,
    },
    pricePerUnit: 91.75,
    asset: 'USDT',
    currency: 'INR',
    minLimit: 1000,
    maxLimit: 15000,
    available: 120.55,
    paymentMethods: ['IMPS', 'UPI', 'Paytm'],
    releaseTime: '90 min',
    type: 'sell',
  },
  {
    id: '7',
    user: {
      name: 'BitWave',
      // avatar: require('@/assets/avatars/bitwave.png'),
      verified: true,
      badge: 'gold',
      trades: 750,
      successRate: 99.1,
      rating: 99.5,
    },
    pricePerUnit: 92.25,
    asset: 'USDT',
    currency: 'INR',
    minLimit: 100000,
    maxLimit: 500000,
    available: 10500.0,
    paymentMethods: ['GPay', 'PhonePe'],
    releaseTime: '25 min',
    type: 'buy',
  },
];

const allFilterItem: FilterItem = { id: 'all', label: 'All' };

export * from './strings';
export * from './styles';
export { allFilterItem, EMAIL_REGEX, NAME_REGEX, PASSWORD_REGEX, PHONE_REGEX, SupabaseConfig };
