const Strings = {
  appName: 'Crypter',
  login: {
    SCREEN_TITLE: "Let's sign you in!",
    EMAIL_LABEL: 'Email Address',
    PASSWORD_LABEL: 'Password',
    BUTTON_LABEL: 'Login',
    OR_CONTINUE_WITH: 'Or continue with',
    NO_ACCOUNT_TEXT: "Don't have an account?",
    SIGNUP_CTA: 'Sign Up',
  },
  signup: {
    SCREEN_TITLE: "Let's sign you up!",
    EMAIL_LABEL: 'Email Address',
    BUTTON_LABEL: 'Continue with Email',
    OR_CONTINUE_WITH: 'Or continue with',
    NO_ACCOUNT_TEXT: 'Already have an account?',
    SIGNIN_CTA: 'Sign In',
  },
  signupInfo: {
    SCREEN_TITLE: 'Almost there...',
    EMAIL_LABEL: 'Email Address',
    NAME_LABEL: 'First Name',
    PHONE_LABEL: 'Phone Number',
    PASSWORD_LABEL: 'Password',
    CONFIRM_PASSWORD_LABEL: 'Confirm Password',
    BUTTON_LABEL: 'Sign Up',
  },
  welcome: {
    SCREEN_GREETING: 'Hello',
    SCREEN_TITLE: 'Welcome to Crypter',
    WELCOME_TEXT: "It's great to have you here!",
    BUTTON_LABEL: "I'm ready to start!",
  },
  home: {
    TAB_TITLE: 'Home',
    HEADER_TITLE: 'Home',
  },
  profile: {
    TAB_TITLE: 'Profile',
    HEADER_TITLE: 'Profile',
    TRADING_STATS_TITLE: 'Trading Stats',
    TOTAL_TRADES_LABEL: 'Total Trades',
    COMPLETION_RATE_LABEL: 'Completion Rate',
    AVG_RELEASE_LABEL: 'Average Release Time',
    AVG_PAY_LABEL: 'Average Pay Time',
    VIEW_MORE_LABEL: 'View More Details',
    MENU_FEEDBACK_TITLE: 'Received Feedback',
    MENU_NOTIF_TITLE: 'Notifications',
    MENU_MERCHANT_TITLE: 'Become a Merchant',
    MENU_PAY_METHODS_TITLE: 'Payment Methods',
    MENU_HELP_TITLE: 'Help Center',
    LOGOUT_BTN_TITLE: 'Log Out',
  },
  editProfile: {
    HEADER_TITLE: 'Edit',
    NAME_LABEL: 'Your name',
    EMAIL_LABEL: 'Email Address',
    PASSWORD_LABEL: 'Your Password',
    PHONE_LABEL: 'Phone Number',
    SAVE_BTN_TITLE: 'Save',
  },
  stats: {
    HEADER_TITLE: 'Trading Stats',
    TRADE_LABEL: 'Trades',
    BUY_LABEL: 'Buy Trades',
    SELL_LABEL: 'Sell Trades',
    COMPLETION_RATE_LABEL: 'Completion Rate',
    AVG_RELEASE_LABEL: 'Average Release Time',
    AVG_PAY_LABEL: 'Average Pay Time',
    FEEDBACK_POSITIVE_LABEL: 'Positive Feedback',
    FEEDBACK_NEGATIVE_LABEL: 'Negative Feedback',
    TOTAL_VOLUME_LABEL: 'Approx Total Volume',
  },
  feedback: {
    HEADER_TITLE: 'Feedback',
  },
  p2p: {
    TAB_TITLE: 'P2P',
    HEADER_TITLE: 'MarketPlace',
  },
  orders: {
    TAB_TITLE: 'Orders',
    HEADER_TITLE: 'Orders',
  },
  myAds: {
    TAB_TITLE: 'Adverts',
    HEADER_TITLE: 'My Adverts',
  },
  postAd: {
    HEADER_TITLE: 'Post Adverts',
    EMPTY_STATE: 'No ads available',
    PRICE_SETTING: 'Price Setting',
    BUTTON_NEXT_LABEL: 'Next Steps',
    HEADER_TITLE_INFO: 'Amount Info',
  },
  errors: {
    EMAIL_ERROR: 'Please enter a valid email address',
  },
  verify: {
    SCREEN_TITLE: 'Become A Verified Crypter P2P Merchant',
    SCREEN_SUBTITLE: 'Become a registered and verified P2P Merchant on the Crypter P2P Market',
    CTA_LABEL: 'Get Started',
  },
  requirements: {
    VERIFY_EMAIL_LABEL: 'Complete email verification',
    VERIFY_PHONE_LABEL: 'Complete phone verification',
    VERIFY_IDENTITY_LABEL: 'Complete identity verification',
    ATTENTION_LABEL: 'Attention',
    ATTENTION_TEXT: 'To become a merchant, you need to verify your identity and contact information',
    CTA_LABEL: 'Send Application',
    TITLE_KYC_SUBMIT: 'Application Sent',
    KYC_SUBMIT: 'Your application has been sent. The P2P team will contact you within a few days if you are qualified.',
  },
  info: {
    NAME_LABEL: 'Full Legal Name',
    NAME_HINT: 'Enter your full name',
    COUNTRY_LABEL: 'Country of Residence',
    COUNTRY_HINT: 'Select country of residence',
    ADDRESS_LABEL: 'Address',
    ADDRESS_HINT: 'Enter your address',
    EMAIL_LABEL: 'Email Address',
    EMAIL_HINT: 'Enter your email address',
    PHONE_LABEL: 'Phone Number',
    PHONE_HINT: 'Enter your phone number',
    UPLOAD_ID_LABEL: 'Upload ID or Passport',
    UPLOAD_ADDRESS_LABEL: 'Upload Address Proof',
    CTA_LABEL: 'Confirm',
  },
  otp: {
    TITLE: 'Enter Code',
    SUBTITLE: 'Enter the code sent to your',
    CODE_NOT_RECEIVED: "Didn't receive code?",
    RESEND_CODE: 'Resend Code',
    RESEND_IN: 'Resend in',
    CTA: 'Confirm OTP',
    OTP_SUCCESS: 'Success',
    EMAIL_SUCCESS: 'Your email address has been verified successfully.',
    PHONE_SUCCESS: 'Your phone number has been verified successfully.',
  },
  verifyIdentity: {
    TITLE_DOC_SUBMIT: 'Documents Submitted',
    DOC_SUBMIT:
      'Your documents are being verified. You will receive a confirmation mail once your verfication is complete.',
  },
};

export * from './alert';
export * from './components';
export * from './toast';
export { Strings };
